### PR TITLE
fix: infinite recursion with SQL params

### LINKED ISSUE #554: Stack Overflow when TS Child Node is smaller than Parent Node
The problem happens when the treesitter parses parses a child node to be smaller than the parent node, and the cursor position is *not* on the child node:

```
@i|d -- parent node with cursor
@    -- child node
```

Image

### PR DESCRIPTION
**Pull request by juleswritescode**
Fixes #554 and maybe #516

### CODE REVIEW

File: crates/pgt_treesitter/src/context/mod.rs [hunk 1]
```diff
@@ -1214,4 +1216,45 @@ mod tests {
             _ => unreachable!(),
         }
     }
+
+    #[test]
+    fn does_not_overflow_callstack_on_smaller_treesitter_child() {
+        //  Instead of autocompleting "FROM", we'll assume that the user
+        // is selecting a certain column name, such as `frozen_account`.
```
Comment (juleswritescode) [inline crates/pgt_treesitter/src/context/mod.rs]:
```suggestion
```
